### ISSUE TITLE
Make available on Maven Central

### ISSUE THREAD

**Issue by nightowlengineer** [nightowlengineer/groupsio-api-java#3]

**Comment by lake54** [comment]
[OSSRH-34974](https://issues.sonatype.org/browse/OSSRH-34974) resolved by Sonatype, pending initial upload.

**Comment by zikphil** [comment]
Any updates on this?

**Comment by nightowlengineer** [comment]
Apologies for the time taken to resolve this. If it's still relevant, artefacts for 0.0.2 have been pushed up and should be available shortly on Maven Central. However, I haven't worked on this dependency for a fair while now, so please do raise any issues you have and I'll try and get onto them a bit quicker next time around!
